services:
  anyshare:
    image: registry.cn-hangzhou.aliyuncs.com/gmoneyltd/anyshare:latest
    container_name: anyshare4play   
    hostname: anyshare4play
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - helloworld
    environment:
      - TZ=Asia/Shanghai
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=123456
      - LOG_LEVEL=DEBUG
      - ANONYMOUS=false
    volumes:
      - ./log:/app/log
      - ./upload:/app/upload
networks:
  helloworld:
    external: true
    name: home4play
