services:
  hwatch:
    image: registry.cn-hangzhou.aliyuncs.com/gmoneyltd/hwatch:latest
    container_name: hwatch4play   
    hostname: hwatch4play
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - helloworld
    environment:
      - TZ=Asia/Shanghai
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=123456
      - LOG_LEVEL=DEBUG
      - ANONYMOUS=false
    volumes:
      - ./log:/app/log
      - ./upload:/app/upload
networks:
  helloworld:
    external: true
    name: home4play
